# Uncomment the next line to define a global platform for your project 
platform :ios, '10.0'

target 'Speech-Drill' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Speech-Drill
  pod 'Mute'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FirebaseStorage'
  pod 'GoogleSignIn'
  pod 'FontAwesome.swift'
  pod 'Firebase/Messaging'
  pod 'Firebase/Analytics'
  pod 'Siren'
  pod 'Willow', '6.0.0'
end
